apiVersion: v1
kind: Service
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  ports:
  - port: 16686
    name: ui
    targetPort: 16686
  - port: 4317
    name: otlp-grpc
    targetPort: 4317
  - port: 4318
    name: otlp-http
    targetPort: 4318
  - port: 14250
    name: model-grpc
    targetPort: 14250
  - port: 14268
    name: collector-http
    targetPort: 14268
  - port: 9411
    name: zipkin
    targetPort: 9411
  selector:
    app: jaeger
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        env:
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
        ports:
        - containerPort: 16686
          name: ui
        - containerPort: 4317
          name: otlp-grpc
        - containerPort: 4318
          name: otlp-http
        - containerPort: 14250
          name: model-grpc
        - containerPort: 14268
          name: collector-http
        - containerPort: 9411
          name: zipkin
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
---
# Optional: For external access to the Jaeger UI
apiVersion: v1
kind: Service
metadata:
  name: jaeger-ui
  labels:
    app: jaeger
spec:
  ports:
  - port: 16686
    targetPort: 16686
    name: ui
  selector:
    app: jaeger
  type: NodePort  # Change to LoadBalancer for cloud environments